name: Cleanup Resources

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/host_key.pub
        chmod 600 ~/.ssh/host_key.pub

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest # Use the latest Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy Terraform Resources
      run: terraform destroy -auto-approve
